server:
    port: 8090
spring:
    data:
        mongodb:
            uri: mongodb+srv://kaveeshkumar:28Mongo@cropdeal.8zc5d.mongodb.net/AdminDetails?retryWrites=true&w=majority
    application:
        name: AdminService
    mvc:
        pathmatch:
            matching-strategy:
                ant-path-matcher