zuul:
  prefix: /api
  routes:
    FarmerService:
      path: /farmer/**
      serviceId: FarmerService
      url : http://localhost:8098/
    DealerService:
      path: /Dealer/**
      serviceId: DealerService
      url: http://localhost:8096/
    CropDetailService:
      path: /Crop/**
      serviceId: CropDetailService
      url: http://localhost:8095
    AdminService:
      path: /Admin/**
      serviceId: AdminService
      url: http://localhost:8090

server:
  port: 9000

spring:
  application:
    name: Api-Service


eureka:
  client:
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    instance:
      preferIpAddress: true
    register-with-eureka: true
