server:
  port: 8096
spring:
  data:
    mongodb:
      uri: mongodb+srv://kaveeshkumar:28Mongo@cropdeal.8zc5d.mongodb.net/DealerDetails?retryWrites=true&w=majority
  application:
    name: DealerService
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher