server:
  port: 8095
spring:
  data:
    mongodb:
      uri: mongodb+srv://kaveeshkumar:28Mongo@cropdeal.8zc5d.mongodb.net/CropDetails?retryWrites=true&w=majority
  application:
    name: CropDetailService
  mvc:
    pathmatch:
      matching-strategy:
        ant-path-matcher